// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/21       [336405]
Creator        : jandrea
Date           : Thu Oct 16 19:06:46 2014
Host           : Linux sbgat230 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/jandrea/WORK/SingleTop_tZ_8TeV/TMVA
Training events: 106973
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "3" [Max depth of the decision tree allowed]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
SeparationType: "giniindex" [Separation criterion for node splitting]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
nEventsMin: "100" [deprecated: Use MinNodeSize (in % of training events) instead]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MinNodeSize: "0.0934823.2" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "5" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 26
tree_cosThetaStar             tree_cosThetaStar             tree_cosThetaStar             tree_cosThetaStar                                               'F'    [-0.999961316586,0.999983429909]
tree_topMass                  tree_topMass                  tree_topMass                  tree_topMass                                                    'F'    [31.2117538452,2874.66333008]
tree_totMass                  tree_totMass                  tree_totMass                  tree_totMass                                                    'F'    [171.15914917,3083.70043945]
tree_deltaPhilb               tree_deltaPhilb               tree_deltaPhilb               tree_deltaPhilb                                                 'F'    [0.000163005664945,3.14156198502]
tree_deltaRlb                 tree_deltaRlb                 tree_deltaRlb                 tree_deltaRlb                                                   'F'    [0.500078141689,5.57961511612]
tree_deltaRTopZ               tree_deltaRTopZ               tree_deltaRTopZ               tree_deltaRTopZ                                                 'F'    [0.0287274923176,9.32327747345]
tree_asym                     tree_asym                     tree_asym                     tree_asym                                                       'F'    [-2.49967575073,2.49931979179]
tree_Zpt                      tree_Zpt                      tree_Zpt                      tree_Zpt                                                        'F'    [0.319067358971,980.141540527]
tree_ZEta                     tree_ZEta                     tree_ZEta                     tree_ZEta                                                       'F'    [-7.42170143127,6.63223838806]
tree_topPt                    tree_topPt                    tree_topPt                    tree_topPt                                                      'F'    [0.218741685152,1395.84863281]
tree_topEta                   tree_topEta                   tree_topEta                   tree_topEta                                                     'F'    [-8.44435596466,7.30331707001]
tree_NJets                    tree_NJets                    tree_NJets                    tree_NJets                                                      'F'    [1,8]
tree_NBJets                   tree_NBJets                   tree_NBJets                   tree_NBJets                                                     'F'    [0,1]
tree_deltaRZl                 tree_deltaRZl                 tree_deltaRZl                 tree_deltaRZl                                                   'F'    [0.0190307311714,8.00830078125]
tree_deltaPhiZmet             tree_deltaPhiZmet             tree_deltaPhiZmet             tree_deltaPhiZmet                                               'F'    [-3.14155340195,3.1415746212]
tree_btagDiscri               tree_btagDiscri               tree_btagDiscri               tree_btagDiscri                                                 'F'    [-10,1]
tree_totPt                    tree_totPt                    tree_totPt                    tree_totPt                                                      'F'    [0.0551481582224,1127.41906738]
tree_totEta                   tree_totEta                   tree_totEta                   tree_totEta                                                     'F'    [-9.14161682129,8.42345714569]
tree_leptWPt                  tree_leptWPt                  tree_leptWPt                  tree_leptWPt                                                    'F'    [20.0017738342,1090.88171387]
tree_leptWEta                 tree_leptWEta                 tree_leptWEta                 tree_leptWEta                                                   'F'    [-2.49967575073,2.49931979179]
tree_leadJetPt                tree_leadJetPt                tree_leadJetPt                tree_leadJetPt                                                  'F'    [30.0015277863,1351.86914062]
tree_leadJetEta               tree_leadJetEta               tree_leadJetEta               tree_leadJetEta                                                 'F'    [-2.49996066093,2.49991059303]
tree_deltaRZleptW             tree_deltaRZleptW             tree_deltaRZleptW             tree_deltaRZleptW                                               'F'    [0.0190307311714,8.00830078125]
tree_deltaPhiZleptW           tree_deltaPhiZleptW           tree_deltaPhiZleptW           tree_deltaPhiZleptW                                             'F'    [-3.14152288437,3.14157891273]
tree_met                      tree_met                      tree_met                      tree_met                                                        'F'    [0.325588166714,834.605712891]
tree_mTW                      tree_mTW                      tree_mTW                      tree_mTW                                                        'F'    [0.000683983322233,966.44744873]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 26 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "tree_cosThetaStar", "tree_topMass", "tree_totMass", "tree_deltaPhilb", "tree_deltaRlb", "tree_deltaRTopZ", "tree_asym", "tree_Zpt", "tree_ZEta", "tree_topPt", "tree_topEta", "tree_NJets", "tree_NBJets", "tree_deltaRZl", "tree_deltaPhiZmet", "tree_btagDiscri", "tree_totPt", "tree_totEta", "tree_leptWPt", "tree_leptWEta", "tree_leadJetPt", "tree_leadJetEta", "tree_deltaRZleptW", "tree_deltaPhiZleptW", "tree_met", "tree_mTW" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;
      fVmin[20] = 0;
      fVmax[20] = 0;
      fVmin[21] = 0;
      fVmax[21] = 0;
      fVmin[22] = 0;
      fVmax[22] = 0;
      fVmin[23] = 0;
      fVmax[23] = 0;
      fVmin[24] = 0;
      fVmax[24] = 0;
      fVmin[25] = 0;
      fVmax[25] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';
      fType[21] = 'F';
      fType[22] = 'F';
      fType[23] = 'F';
      fType[24] = 'F';
      fType[25] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[26];
   double fVmax[26];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[26];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.684488706525866);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 34.7087, 0, 1, 0.965333,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.823536,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459238,-99) , 
16, 38.1033, 0, 0, 0.73618,-99) , 
15, 0.850354, 0, 0, 0.902786,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536639,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.315489,-99) , 
18, 99.9648, 1, 0, 0.507522,-99) , 
NN(
0, 
0, 
-1, 33.2878, 0, -1, 0.176931,-99) , 
16, 53.7391, 0, 0, 0.282955,-99) , 
15, 0.47619, 0, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.517472);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 34.7087, 0, 1, 0.94238,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.746388,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469283,-99) , 
1, 265.888, 1, 0, 0.697165,-99) , 
15, 0.875295, 0, 0, 0.855114,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573031,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430715,-99) , 
20, 66.6014, 0, 0, 0.483578,-99) , 
NN(
0, 
0, 
-1, -1.78585, 1, -1, 0.292071,-99) , 
12, 0.047619, 0, 0, 0.329217,-99) , 
15, 0.47619, 0, 0, 0.496633,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.330828);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.825414, 0, 1, 0.798873,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.632589,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439853,-99) , 
20, 53.1799, 0, 0, 0.571031,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55202,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392195,-99) , 
21, 1.68361, 0, 0, 0.414452,-99) , 
21, -1.78569, 1, 0, 0.431225,-99) , 
15, 0.47619, 0, 0, 0.540105,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.204316);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 34.7087, 0, 1, 0.892966,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.695318,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477429,-99) , 
16, 74.5519, 0, 0, 0.571397,-99) , 
15, 0.900236, 0, 0, 0.740475,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513294,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366582,-99) , 
6, 1.53583, 1, 0, 0.493294,-99) , 
NN(
0, 
0, 
-1, 28.1972, 0, -1, 0.308776,-99) , 
6, -1.54749, 0, 0, 0.480196,-99) , 
15, 0.47619, 0, 0, 0.553565,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.235964);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 34.7087, 0, 1, 0.835125,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.610041,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449879,-99) , 
20, 63.7327, 0, 0, 0.519173,-99) , 
15, 0.825414, 0, 0, 0.728799,-99) , 
NN(
NN(
0, 
0, 
-1, 1.33333, 1, 1, 0.564268,-99) , 
NN(
0, 
0, 
-1, 25.6143, 0, -1, 0.433497,-99) , 
16, 107.423, 0, 0, 0.448986,-99) , 
15, 0.47619, 0, 0, 0.525371,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.186079);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 304.882, 1, 1, 0.873374,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.654402,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487264,-99) , 
15, 0.732769, 0, 0, 0.580992,-99) , 
15, 0.925177, 0, 0, 0.704406,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554516,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475548,-99) , 
6, 1.00304, 1, 0, 0.52324,-99) , 
NN(
0, 
0, 
-1, 28.3419, 0, -1, 0.438209,-99) , 
6, -0.119202, 0, 0, 0.493697,-99) , 
15, 0.47619, 0, 0, 0.549383,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.184069);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 304.882, 1, 1, 0.886321,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.642247,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468909,-99) , 
16, 37.4649, 0, 0, 0.593905,-99) , 
15, 0.950118, 0, 0, 0.688961,-99) , 
NN(
NN(
0, 
0, 
-1, 578.497, 0, 1, 0.532131,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536962,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.336497,-99) , 
16, 38.2956, 0, 0, 0.446816,-99) , 
0, 0.2381, 1, 0, 0.503553,-99) , 
15, 0.47619, 0, 0, 0.551453,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.195608);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.899507,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474685,-99) , 
1, 304.882, 1, 0, 0.866415,-99) , 
NN(
0, 
0, 
-1, 2.37458, 1, 1, 0.575147,-99) , 
15, 0.950118, 0, 0, 0.66648,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593993,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386446,-99) , 
1, 246.585, 1, 0, 0.532438,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570847,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435923,-99) , 
1, 437.419, 0, 0, 0.454483,-99) , 
12, 0.047619, 0, 0, 0.471211,-99) , 
15, 0.47619, 0, 0, 0.520626,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.128649);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 239.211, 1, 1, 0.85058,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595412,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454943,-99) , 
4, 2.37458, 1, 0, 0.526793,-99) , 
15, 0.950118, 0, 0, 0.624176,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576146,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452384,-99) , 
16, 26.5592, 0, 0, 0.543529,-99) , 
NN(
0, 
0, 
-1, -3.28659, 0, -1, 0.478084,-99) , 
21, -1.07143, 1, 0, 0.494632,-99) , 
15, 0.47619, 0, 0, 0.526951,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.122285);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 239.211, 1, 1, 0.833482,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550668,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.35385,-99) , 
18, 92.8187, 1, 0, 0.526293,-99) , 
15, 0.950118, 0, 0, 0.616315,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53451,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476994,-99) , 
13, 1.92247, 0, 0, 0.518579,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535848,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.278708,-99) , 
4, 1.79594, 1, 0, 0.309358,-99) , 
18, 172.985, 1, 0, 0.514853,-99) , 
15, 0.47619, 0, 0, 0.539867,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.150211);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 239.211, 1, 1, 0.815812,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572237,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454982,-99) , 
16, 74.5519, 0, 0, 0.503349,-99) , 
15, 0.950118, 0, 0, 0.592735,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57992,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449737,-99) , 
16, 37.8951, 0, 0, 0.520941,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504226,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426507,-99) , 
13, 2.51431, 0, 0, 0.46648,-99) , 
7, 93.791, 1, 0, 0.501899,-99) , 
15, 0.47619, 0, 0, 0.524071,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.0984501);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.821825,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480691,-99) , 
16, 34.7087, 0, 0, 0.757011,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504323,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.249905,-99) , 
18, 141.366, 1, 0, 0.493275,-99) , 
15, 0.925177, 0, 0, 0.588426,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542953,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487123,-99) , 
16, 37.8951, 0, 0, 0.517597,-99) , 
NN(
0, 
0, 
-1, 63.7097, 0, -1, 0.465208,-99) , 
7, 93.791, 1, 0, 0.499228,-99) , 
15, 0.47619, 0, 0, 0.520815,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.103511);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.762592,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481053,-99) , 
15, 0.925177, 0, 0, 0.581824,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531833,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480249,-99) , 
16, 53.7391, 1, 0, 0.512157,-99) , 
15, 0.47619, 0, 0, 0.528946,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.826824,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494385,-99) , 
20, 62.6418, 0, 0, 0.733401,-99) , 
NN(
0, 
0, 
-1, 168.14, 1, -1, 0.371566,-99) , 
4, 1.18348, 1, 0, 0.402006,-99) , 
18, 121.99, 1, 0, 0.52154,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.109861);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.838094,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480618,-99) , 
1, 239.211, 1, 0, 0.768658,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533757,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39596,-99) , 
15, 0.566503, 0, 0, 0.508703,-99) , 
15, 0.950118, 0, 0, 0.578307,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541498,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438787,-99) , 
11, 2.14286, 1, 0, 0.531758,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514582,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444584,-99) , 
5, 3.13199, 1, 0, 0.481056,-99) , 
24, 64.626, 0, 0, 0.502015,-99) , 
15, 0.47619, 0, 0, 0.520259,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0594341);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.821436,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495444,-99) , 
16, 34.7087, 0, 0, 0.759753,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523485,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414434,-99) , 
6, -0.348169, 0, 0, 0.491198,-99) , 
15, 0.950118, 0, 0, 0.561761,-99) , 
NN(
0, 
0, 
-1, 4.2413, 1, -1, 0.492113,-99) , 
15, 0.47619, 0, 0, 0.508671,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0655087);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.47619, 0, 1, 0.526804,-99) , 
NN(
0, 
0, 
-1, 30.7645, 0, -1, 0.408214,-99) , 
6, -1.78008, 0, 0, 0.521734,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.716104,-99) , 
NN(
0, 
0, 
-1, 0.047619, 1, -1, 0.291671,-99) , 
4, 1.3613, 1, 0, 0.329596,-99) , 
18, 172.985, 1, 0, 0.518388,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.151883);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.47619, 0, 1, 0.549928,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.686881,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427533,-99) , 
11, 1.2381, 0, 0, 0.469772,-99) , 
16, 37.8951, 0, 0, 0.51757,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.636237,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449633,-99) , 
16, 37.4182, 0, 0, 0.573265,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539856,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383708,-99) , 
4, 3.3585, 0, 0, 0.413412,-99) , 
1, 189.854, 1, 0, 0.460537,-99) , 
18, 70.9961, 1, 0, 0.503919,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0717217);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.76078,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466032,-99) , 
15, 0.950118, 0, 0, 0.540273,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.600081,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491177,-99) , 
1, 708.224, 0, 0, 0.494452,-99) , 
15, 0.47619, 0, 0, 0.505279,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5456,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43255,-99) , 
20, 57.1387, 0, 0, 0.498941,-99) , 
NN(
0, 
0, 
-1, 238.468, 1, -1, 0.420706,-99) , 
0, -0.237674, 1, 0, 0.449199,-99) , 
6, -1.07139, 0, 0, 0.497643,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0665882);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525885,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424639,-99) , 
17, 4.2413, 1, 0, 0.522827,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.705112,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.343301,-99) , 
4, 1.3613, 1, 0, 0.378269,-99) , 
18, 172.985, 1, 0, 0.520289,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593115,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473973,-99) , 
15, 0.904762, 0, 0, 0.483628,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56208,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405721,-99) , 
21, -1.78413, 1, 0, 0.423956,-99) , 
0, 0.143109, 1, 0, 0.459249,-99) , 
6, -1.07139, 0, 0, 0.511998,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.106578);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.19326, 1, 1, 0.532261,-99) , 
NN(
0, 
0, 
-1, 33.8549, 0, -1, 0.367028,-99) , 
20, 38.9933, 0, 0, 0.50502,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.628346,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410325,-99) , 
12, 0.047619, 1, 0, 0.58583,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522295,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.348319,-99) , 
21, -1.13317, 1, 0, 0.392757,-99) , 
21, 1.06906, 0, 0, 0.43414,-99) , 
20, 218.84, 1, 0, 0.500757,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0796848);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.761898,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495741,-99) , 
15, 0.964001, 0, 0, 0.524652,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512517,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436022,-99) , 
20, 66.0126, 0, 0, 0.477051,-99) , 
12, 0.047619, 0, 0, 0.495888,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508136,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418002,-99) , 
16, 36.6069, 0, 0, 0.474281,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582397,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.35745,-99) , 
16, 55.6953, 1, 0, 0.390786,-99) , 
11, 2.14286, 1, 0, 0.463137,-99) , 
7, 93.6355, 1, 0, 0.484305,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0833691);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.928001, 0, 1, 0.540341,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529394,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457817,-99) , 
21, 1.0706, 0, 0, 0.475532,-99) , 
12, 0.047619, 0, 0, 0.501183,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508693,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449664,-99) , 
20, 92.9487, 0, 0, 0.475521,-99) , 
NN(
0, 
0, 
-1, 0.047619, 1, -1, 0.409332,-99) , 
13, 1.76597, 0, 0, 0.46056,-99) , 
7, 93.6355, 1, 0, 0.486827,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0322579);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503249,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471365,-99) , 
7, 93.6355, 1, 0, 0.491997,-99) , 
NN(
0, 
0, 
-1, 76.3257, 1, -1, 0.395082,-99) , 
19, 2.02323, 1, 0, 0.489121,-99) , 
NN(
0, 
0, 
-1, 265.297, 1, -1, 0.27024,-99) , 
18, 223.979, 1, 0, 0.487934,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0981198);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.811087,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485367,-99) , 
15, 0.950118, 0, 0, 0.568753,-99) , 
NN(
0, 
0, 
-1, 218.841, 1, -1, 0.483433,-99) , 
15, 0.47619, 0, 0, 0.506158,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567238,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453593,-99) , 
20, 42.5386, 0, 0, 0.526784,-99) , 
NN(
0, 
0, 
-1, 0.047619, 1, -1, 0.445064,-99) , 
1, 196.929, 1, 0, 0.47353,-99) , 
4, 2.19326, 1, 0, 0.485919,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0563077);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.732209,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477646,-99) , 
15, 0.900236, 0, 0, 0.581436,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513129,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393611,-99) , 
20, 218.841, 1, 0, 0.507956,-99) , 
15, 0.47619, 0, 0, 0.527423,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504957,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.380345,-99) , 
16, 189.255, 1, 0, 0.501656,-99) , 
NN(
0, 
0, 
-1, 0.47619, 1, -1, 0.446748,-99) , 
18, 70.9961, 1, 0, 0.486971,-99) , 
4, 2.19326, 1, 0, 0.50235,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.064187);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.950118, 0, 1, 0.584547,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564192,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486915,-99) , 
18, 87.7317, 0, 0, 0.495096,-99) , 
15, 0.47619, 0, 0, 0.518706,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513092,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471735,-99) , 
11, 1.28571, 1, 0, 0.496026,-99) , 
NN(
0, 
0, 
-1, 179.926, 1, -1, 0.447272,-99) , 
24, 40.0532, 0, 0, 0.48095,-99) , 
4, 2.19326, 1, 0, 0.495293,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0913055);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.33333, 1, 1, 0.584286,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540069,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42371,-99) , 
16, 25.7928, 0, 0, 0.509673,-99) , 
16, 107.587, 0, 0, 0.523834,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549431,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44318,-99) , 
16, 30.6967, 0, 0, 0.514008,-99) , 
NN(
0, 
0, 
-1, 0.047619, 1, -1, 0.46785,-99) , 
1, 196.929, 1, 0, 0.483944,-99) , 
4, 2.19326, 1, 0, 0.499094,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0654526);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.2381, 0, 1, 0.564786,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546525,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476436,-99) , 
11, 1.28571, 1, 0, 0.50486,-99) , 
16, 37.2996, 1, 0, 0.524473,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516021,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46248,-99) , 
25, 83.2252, 1, 0, 0.501175,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506518,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366924,-99) , 
20, 47.7022, 0, 0, 0.421233,-99) , 
1, 121.753, 0, 0, 0.49274,-99) , 
24, 79.7808, 0, 0, 0.501676,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0533284);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.833149, 0, 1, 0.52415,-99) , 
NN(
0, 
0, 
-1, -1.92409, 1, -1, 0.360662,-99) , 
24, 295.445, 1, 0, 0.521258,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513455,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469338,-99) , 
1, 207.992, 1, 0, 0.49388,-99) , 
NN(
0, 
0, 
-1, 65.524, 1, -1, 0.424448,-99) , 
1, 121.753, 0, 0, 0.486581,-99) , 
24, 79.7808, 0, 0, 0.496339,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0529264);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.61934,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.338758,-99) , 
15, 0.714285, 1, 0, 0.600771,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.298092,-99) , 
4, 2.72346, 0, 0, 0.578501,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515822,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479407,-99) , 
3, 2.09444, 1, 0, 0.497279,-99) , 
NN(
0, 
0, 
-1, 66.2108, 1, -1, 0.435102,-99) , 
1, 127.925, 0, 0, 0.490276,-99) , 
1, 708.224, 0, 0, 0.492752,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0270693);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.598863,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467205,-99) , 
4, 3.17875, 0, 0, 0.55399,-99) , 
NN(
0, 
0, 
-1, 129.12, 0, -1, 0.49282,-99) , 
1, 545.618, 0, 0, 0.496525,-99) , 
NN(
0, 
0, 
-1, 76.3257, 1, -1, 0.415004,-99) , 
19, 2.02323, 1, 0, 0.494132,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0137878);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 545.618, 0, 1, 0.503763,-99) , 
NN(
0, 
0, 
-1, 265.297, 1, -1, 0.311058,-99) , 
18, 223.979, 1, 0, 0.502753,-99) , 
NN(
0, 
0, 
-1, 76.3257, 1, -1, 0.42159,-99) , 
19, 2.02323, 1, 0, 0.500374,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0419795);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 89.3303, 0, 1, 0.535151,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537008,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447483,-99) , 
25, 45.0045, 1, 0, 0.47208,-99) , 
0, 0.619165, 1, 0, 0.523282,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560424,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490213,-99) , 
9, 180.739, 0, 0, 0.494794,-99) , 
NN(
0, 
0, 
-1, 2.11652, 0, -1, 0.43951,-99) , 
7, 186.952, 1, 0, 0.490527,-99) , 
14, -2.24396, 1, 0, 0.497164,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0272079);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.834362, 0, 1, 0.585515,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506972,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456979,-99) , 
1, 127.925, 0, 0, 0.501359,-99) , 
1, 708.224, 0, 0, 0.503608,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.22249,-99) , 
18, 274.973, 1, 0, 0.50298,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0130162);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.834362, 0, 1, 0.578897,-99) , 
NN(
0, 
0, 
-1, -1.78553, 0, -1, 0.496083,-99) , 
1, 708.224, 0, 0, 0.498292,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.227233,-99) , 
18, 274.973, 1, 0, 0.497692,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0245174);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506717,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416934,-99) , 
19, 2.09124, 1, 0, 0.504554,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.59888,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439644,-99) , 
21, -2.26184, 1, 0, 0.44947,-99) , 
19, -1.78553, 0, 0, 0.501373,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.229526,-99) , 
18, 274.973, 1, 0, 0.500772,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0344417);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.589874,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.317859,-99) , 
15, 0.714285, 1, 0, 0.571997,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514709,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485912,-99) , 
7, 46.9773, 1, 0, 0.494474,-99) , 
1, 708.224, 0, 0, 0.496491,-99) , 
NN(
0, 
0, 
-1, 2.24576, 0, -1, 0.323728,-99) , 
18, 223.979, 1, 0, 0.49561,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0553404);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 176.968, 1, 1, 0.516648,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516415,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429417,-99) , 
20, 41.9912, 0, 0, 0.490435,-99) , 
20, 92.9476, 0, 0, 0.499405,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.240119,-99) , 
18, 274.973, 1, 0, 0.498841,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0383671);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51976,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491629,-99) , 
20, 92.9486, 0, 0, 0.501479,-99) , 
NN(
0, 
0, 
-1, 60.2878, 1, -1, 0.420694,-99) , 
6, 2.09124, 1, 0, 0.498105,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501195,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462931,-99) , 
23, -1.34631, 1, 0, 0.475298,-99) , 
NN(
0, 
0, 
-1, 230.983, 1, -1, 0.333995,-99) , 
18, 151.059, 1, 0, 0.471666,-99) , 
6, -0.357249, 0, 0, 0.490477,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0574716);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.695439,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470678,-99) , 
11, 1.33333, 1, 0, 0.523339,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500078,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407888,-99) , 
16, 14.4697, 0, 0, 0.488808,-99) , 
16, 75.735, 0, 0, 0.497609,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.643726,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488178,-99) , 
15, 0.904762, 0, 0, 0.500632,-99) , 
NN(
0, 
0, 
-1, 1.28571, 1, -1, 0.401764,-99) , 
13, 2.6016, 0, 0, 0.452875,-99) , 
7, 186.952, 1, 0, 0.493742,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0405381);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516172,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489665,-99) , 
12, 0.047619, 0, 0, 0.500078,-99) , 
NN(
0, 
0, 
-1, 60.2878, 1, -1, 0.424956,-99) , 
6, 2.09124, 1, 0, 0.496944,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506381,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461777,-99) , 
9, 130.969, 0, 0, 0.472138,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.241085,-99) , 
18, 203.482, 1, 0, 0.470285,-99) , 
6, -0.357249, 0, 0, 0.489253,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0502547);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.904762, 0, 1, 0.565764,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550018,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479124,-99) , 
11, 1.2381, 0, 0, 0.497936,-99) , 
16, 73.0041, 0, 0, 0.51445,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544356,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491619,-99) , 
5, 3.278, 1, 0, 0.524444,-99) , 
NN(
0, 
0, 
-1, 158.305, 1, -1, 0.479855,-99) , 
14, -2.62865, 1, 0, 0.486886,-99) , 
14, 2.24398, 0, 0, 0.492605,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0078079);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 708.224, 0, 1, 0.502392,-99) , 
NN(
0, 
0, 
-1, 968.788, 0, -1, 0.324366,-99) , 
24, 318.147, 1, 0, 0.501688,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521882,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.32147,-99) , 
18, 245.121, 1, 0, 0.401206,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.216946,-99) , 
0, 0.716528, 1, 0, 0.343568,-99) , 
18, 223.979, 1, 0, 0.500897,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.00949742);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577219,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498554,-99) , 
1, 708.224, 0, 0, 0.50044,-99) , 
NN(
0, 
0, 
-1, 968.788, 0, -1, 0.32608,-99) , 
24, 318.147, 1, 0, 0.499752,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519933,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.323176,-99) , 
18, 245.121, 1, 0, 0.401515,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.218275,-99) , 
0, 0.716528, 1, 0, 0.344248,-99) , 
18, 223.979, 1, 0, 0.498975,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0258353);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515863,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492004,-99) , 
24, 60.803, 0, 0, 0.502701,-99) , 
NN(
0, 
0, 
-1, 968.788, 0, -1, 0.32817,-99) , 
24, 318.147, 1, 0, 0.502013,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517562,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.325256,-99) , 
18, 245.121, 1, 0, 0.401892,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.2199,-99) , 
0, 0.716528, 1, 0, 0.345078,-99) , 
18, 223.979, 1, 0, 0.50123,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0566091);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.696662,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494696,-99) , 
11, 1.33333, 1, 0, 0.543102,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508996,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445617,-99) , 
16, 54.1098, 1, 0, 0.495665,-99) , 
16, 75.735, 0, 0, 0.50725,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512987,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450896,-99) , 
0, -0.618878, 0, 0, 0.499959,-99) , 
NN(
0, 
0, 
-1, 1.26797, 1, -1, 0.434405,-99) , 
13, 2.2619, 0, 0, 0.476408,-99) , 
7, 140.294, 1, 0, 0.501932,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0106014);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58226,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498392,-99) , 
1, 705.733, 0, 0, 0.500233,-99) , 
NN(
0, 
0, 
-1, 78.9688, 0, -1, 0.402816,-99) , 
24, 238.691, 1, 0, 0.499036,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50411,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.327217,-99) , 
18, 245.121, 1, 0, 0.397651,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.223147,-99) , 
0, 0.716528, 1, 0, 0.343495,-99) , 
18, 223.979, 1, 0, 0.498261,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.00930028);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 593.312, 0, 1, 0.502767,-99) , 
NN(
0, 
0, 
-1, 78.9688, 0, -1, 0.405369,-99) , 
24, 238.691, 1, 0, 0.501571,-99) , 
NN(
0, 
0, 
-1, 0.716528, 1, -1, 0.344428,-99) , 
18, 223.979, 1, 0, 0.500789,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0133308);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546917,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49836,-99) , 
1, 545.618, 0, 0, 0.501151,-99) , 
NN(
0, 
0, 
-1, 76.3257, 1, -1, 0.437852,-99) , 
19, 2.02323, 1, 0, 0.499303,-99) , 
NN(
0, 
0, 
-1, 0.716528, 1, -1, 0.346531,-99) , 
18, 223.979, 1, 0, 0.498544,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0172929);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505322,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407981,-99) , 
24, 238.691, 1, 0, 0.5041,-99) , 
NN(
0, 
0, 
-1, 76.3257, 1, -1, 0.441136,-99) , 
19, 2.02323, 1, 0, 0.502264,-99) , 
NN(
0, 
0, 
-1, 0.716528, 1, -1, 0.349556,-99) , 
18, 223.979, 1, 0, 0.501507,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0184656);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504458,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479803,-99) , 
6, -0.595297, 0, 0, 0.498755,-99) , 
NN(
0, 
0, 
-1, -0.216137, 0, -1, 0.30891,-99) , 
18, 235.73, 1, 0, 0.498068,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.26636,-99) , 
7, 466.901, 1, 0, 0.497582,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0118223);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.695471,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495733,-99) , 
1, 1249.83, 0, 0, 0.496273,-99) , 
NN(
0, 
0, 
-1, -0.216137, 0, -1, 0.312866,-99) , 
18, 235.73, 1, 0, 0.495612,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.269984,-99) , 
7, 466.901, 1, 0, 0.495141,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.00591113);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.692961,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498688,-99) , 
1, 1249.83, 0, 0, 0.499213,-99) , 
NN(
0, 
0, 
-1, -0.216137, 0, -1, 0.315413,-99) , 
18, 235.73, 1, 0, 0.498551,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.27232,-99) , 
7, 466.901, 1, 0, 0.49808,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0169336);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504664,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475334,-99) , 
7, 155.634, 1, 0, 0.500683,-99) , 
NN(
0, 
0, 
-1, -0.216137, 0, -1, 0.316691,-99) , 
18, 235.73, 1, 0, 0.500021,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.273493,-99) , 
7, 466.901, 1, 0, 0.49955,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0427605);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 39.5007, 1, 1, 0.586002,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502603,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.289529,-99) , 
10, -2.33921, 1, 0, 0.360278,-99) , 
16, 102.934, 1, 0, 0.553404,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.701498,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487175,-99) , 
11, 1.33333, 1, 0, 0.523123,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502607,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43511,-99) , 
16, 20.5062, 0, 0, 0.489651,-99) , 
16, 107.423, 0, 0, 0.494736,-99) , 
21, -2.26187, 1, 0, 0.496507,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0785782);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 185.359, 1, 1, 0.692337,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53351,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394754,-99) , 
1, 310.174, 1, 0, 0.493167,-99) , 
11, 1.33333, 1, 0, 0.525958,-99) , 
NN(
NN(
0, 
0, 
-1, 1.2381, 1, 1, 0.561221,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524118,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468503,-99) , 
21, -1.30952, 1, 0, 0.479456,-99) , 
16, 86.972, 0, 0, 0.485798,-99) , 
16, 107.423, 0, 0, 0.49187,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0147488);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502026,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.348788,-99) , 
24, 318.147, 1, 0, 0.501405,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.269984,-99) , 
18, 274.973, 1, 0, 0.500936,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430143,-99) , 
11, 1.19048, 1, 0, 0.479987,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.660654,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.369606,-99) , 
11, 1.09524, 0, 0, 0.40941,-99) , 
16, 30.7645, 0, 0, 0.456283,-99) , 
19, -1.78553, 0, 0, 0.498364,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0218065);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530854,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492341,-99) , 
9, 199.594, 0, 0, 0.496032,-99) , 
NN(
0, 
0, 
-1, -0.216137, 0, -1, 0.324032,-99) , 
18, 235.73, 1, 0, 0.495423,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.279104,-99) , 
7, 466.901, 1, 0, 0.49498,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0345317);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512935,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.316714,-99) , 
24, 193.227, 1, 0, 0.510745,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518837,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481415,-99) , 
23, 2.24398, 0, 0, 0.490134,-99) , 
7, 66.8824, 1, 0, 0.499833,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.283513,-99) , 
7, 466.901, 1, 0, 0.499392,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0133504);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544568,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496426,-99) , 
1, 572.822, 0, 0, 0.4989,-99) , 
NN(
0, 
0, 
-1, -0.216137, 0, -1, 0.329407,-99) , 
18, 235.73, 1, 0, 0.498301,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.290579,-99) , 
7, 466.901, 1, 0, 0.49788,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0207519);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504991,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429023,-99) , 
18, 165.537, 1, 0, 0.503636,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.280664,-99) , 
18, 274.973, 1, 0, 0.503189,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530045,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440576,-99) , 
11, 1.19048, 1, 0, 0.486226,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.662395,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.377627,-99) , 
11, 1.09524, 0, 0, 0.416742,-99) , 
16, 30.7645, 0, 0, 0.462939,-99) , 
19, -1.78553, 0, 0, 0.500877,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.00948445);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.679782,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496492,-99) , 
1, 1249.83, 0, 0, 0.496998,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.213266,-99) , 
18, 297.366, 1, 0, 0.496665,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.29056,-99) , 
7, 466.901, 1, 0, 0.496248,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.00873959);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556758,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497806,-99) , 
1, 708.224, 0, 0, 0.499356,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.214862,-99) , 
18, 297.366, 1, 0, 0.499023,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.292519,-99) , 
7, 466.901, 1, 0, 0.498606,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0186698);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.18627, 1, 1, 0.519466,-99) , 
NN(
0, 
0, 
-1, 0.983844, 0, -1, 0.496397,-99) , 
9, 133.136, 0, 0, 0.502115,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.631264,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451188,-99) , 
4, 3.36565, 0, 0, 0.474325,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500361,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.30767,-99) , 
0, -0.258442, 0, 0, 0.34087,-99) , 
7, 80.9702, 0, 0, 0.440291,-99) , 
24, 198.964, 1, 0, 0.500677,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0195533);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507452,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480813,-99) , 
7, 155.634, 1, 0, 0.503817,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.215927,-99) , 
18, 297.366, 1, 0, 0.503479,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.293034,-99) , 
7, 466.901, 1, 0, 0.503054,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.00285754);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.674323,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499783,-99) , 
1, 1249.83, 0, 0, 0.500263,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.219256,-99) , 
18, 297.366, 1, 0, 0.499935,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.297101,-99) , 
7, 466.901, 1, 0, 0.499527,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.00340591);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1249.83, 0, 1, 0.500973,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.219745,-99) , 
18, 297.366, 1, 0, 0.500646,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.297698,-99) , 
7, 466.901, 1, 0, 0.500238,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.00311161);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.672946,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499646,-99) , 
1, 1249.83, 0, 0, 0.500122,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.22033,-99) , 
18, 297.366, 1, 0, 0.499796,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.298411,-99) , 
7, 466.901, 1, 0, 0.499392,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.00324039);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1249.83, 0, 1, 0.500896,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.220865,-99) , 
18, 297.366, 1, 0, 0.50057,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.299062,-99) , 
7, 466.901, 1, 0, 0.500165,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.00315689);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.671547,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499614,-99) , 
1, 1249.83, 0, 0, 0.500085,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.221423,-99) , 
18, 297.366, 1, 0, 0.499762,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.299742,-99) , 
7, 466.901, 1, 0, 0.49936,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0103698);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502797,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459127,-99) , 
5, 4.8973, 1, 0, 0.50087,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.221968,-99) , 
18, 297.366, 1, 0, 0.500547,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.300405,-99) , 
7, 466.901, 1, 0, 0.500145,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.00635402);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.682956,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498248,-99) , 
1, 1249.83, 0, 0, 0.498743,-99) , 
NN(
0, 
0, 
-1, -0.216137, 0, -1, 0.340111,-99) , 
18, 235.73, 1, 0, 0.498188,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.302589,-99) , 
7, 466.901, 1, 0, 0.497797,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.00317701);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.681579,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499837,-99) , 
1, 1249.83, 0, 0, 0.500323,-99) , 
NN(
0, 
0, 
-1, -0.216137, 0, -1, 0.341539,-99) , 
18, 235.73, 1, 0, 0.499768,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.303932,-99) , 
7, 466.901, 1, 0, 0.499377,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0040931);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1249.83, 0, 1, 0.501113,-99) , 
NN(
0, 
0, 
-1, -0.216137, 0, -1, 0.342254,-99) , 
18, 235.73, 1, 0, 0.500558,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.304604,-99) , 
7, 466.901, 1, 0, 0.500167,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.00875353);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573327,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499284,-99) , 
1, 705.733, 0, 0, 0.500825,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.234989,-99) , 
18, 297.366, 1, 0, 0.500494,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.624888,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457116,-99) , 
4, 3.36565, 0, 0, 0.478664,-99) , 
NN(
0, 
0, 
-1, -0.627238, 0, -1, 0.338563,-99) , 
7, 80.9702, 0, 0, 0.442872,-99) , 
24, 198.964, 1, 0, 0.499155,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0121729);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539746,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49997,-99) , 
9, 199.594, 0, 0, 0.503368,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568925,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.339874,-99) , 
0, 0.245908, 1, 0, 0.389264,-99) , 
18, 204.911, 1, 0, 0.502592,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.622834,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459289,-99) , 
4, 3.36565, 0, 0, 0.480281,-99) , 
NN(
0, 
0, 
-1, -0.627238, 0, -1, 0.340526,-99) , 
7, 80.9702, 0, 0, 0.444603,-99) , 
24, 198.964, 1, 0, 0.501245,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0112041);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1249.83, 0, 1, 0.504708,-99) , 
NN(
0, 
0, 
-1, -0.216137, 0, -1, 0.346241,-99) , 
18, 235.73, 1, 0, 0.504157,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.306258,-99) , 
7, 466.901, 1, 0, 0.503762,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.00943786);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 705.733, 0, 1, 0.50266,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.240062,-99) , 
18, 297.366, 1, 0, 0.502336,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.617351,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459757,-99) , 
4, 3.36565, 0, 0, 0.47994,-99) , 
NN(
0, 
0, 
-1, -0.627238, 0, -1, 0.34079,-99) , 
7, 80.9702, 0, 0, 0.444409,-99) , 
24, 198.964, 1, 0, 0.500991,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.0747844);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.600043,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495727,-99) , 
12, 0.047619, 1, 0, 0.574924,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511821,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417335,-99) , 
20, 40.5549, 0, 0, 0.487657,-99) , 
20, 103.876, 0, 0, 0.511999,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.642867,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480009,-99) , 
15, 0.928001, 0, 0, 0.511493,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517409,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465824,-99) , 
21, -1.23017, 1, 0, 0.48123,-99) , 
12, 0.047619, 0, 0, 0.493053,-99) , 
21, 0.833287, 0, 0, 0.498737,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.0507124);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.964001, 0, 1, 0.51911,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527716,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48294,-99) , 
1, 288.415, 0, 0, 0.496612,-99) , 
12, 0.047619, 0, 0, 0.505343,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.596593,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474656,-99) , 
1, 330.643, 0, 0, 0.523945,-99) , 
NN(
0, 
0, 
-1, 1.92185, 0, -1, 0.392394,-99) , 
20, 52.4611, 0, 0, 0.475405,-99) , 
21, 1.78564, 1, 0, 0.502301,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0596155);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520756,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469101,-99) , 
11, 2.33333, 1, 0, 0.515286,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529717,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450259,-99) , 
11, 1.2381, 0, 0, 0.477028,-99) , 
5, 3.56951, 1, 0, 0.506626,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540546,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474809,-99) , 
20, 66.1759, 0, 0, 0.510718,-99) , 
NN(
0, 
0, 
-1, 93.1439, 0, -1, 0.453379,-99) , 
5, 3.08099, 0, 0, 0.484489,-99) , 
21, -1.07143, 0, 0, 0.501228,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.0223056);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503928,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473885,-99) , 
1, 131.725, 0, 0, 0.499973,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.695742,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422809,-99) , 
4, 1.17531, 1, 0, 0.443374,-99) , 
18, 143.275, 1, 0, 0.498142,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599851,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451267,-99) , 
4, 3.36565, 0, 0, 0.469932,-99) , 
NN(
0, 
0, 
-1, -0.627238, 0, -1, 0.331459,-99) , 
7, 80.9702, 0, 0, 0.434513,-99) , 
24, 198.964, 1, 0, 0.496663,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.016337);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 223.979, 1, -1, 0.497973,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571178,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462187,-99) , 
21, -2.26184, 1, 0, 0.468286,-99) , 
19, -1.42282, 0, 0, 0.494608,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510176,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389125,-99) , 
7, 125.895, 1, 0, 0.487449,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510024,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.342777,-99) , 
14, 2.54358, 0, 0, 0.365238,-99) , 
25, 76.3257, 1, 0, 0.440355,-99) , 
19, 2.02323, 1, 0, 0.493034,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.0172531);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502787,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.361657,-99) , 
18, 223.979, 1, 0, 0.502057,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514521,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458124,-99) , 
25, 44.9263, 1, 0, 0.471895,-99) , 
19, -1.42282, 0, 0, 0.49864,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500269,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.3433,-99) , 
21, -1.30952, 0, 0, 0.484891,-99) , 
NN(
0, 
0, 
-1, -0.326031, 1, -1, 0.367928,-99) , 
25, 76.3257, 1, 0, 0.439869,-99) , 
19, 2.02323, 1, 0, 0.496937,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.0130218);
  fForest.push_back( 
NN(
0, 
0, 
-1, 2.02323, 1, -1, 0.493489,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.0065109);
  fForest.push_back( 
NN(
0, 
0, 
-1, 2.02323, 1, -1, 0.496745,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.00679431);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500902,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.294898,-99) , 
7, 466.901, 1, 0, 0.500525,-99) , 
NN(
0, 
0, 
-1, 3.18126, 0, -1, 0.364647,-99) , 
24, 318.147, 1, 0, 0.499988,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500839,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.35164,-99) , 
21, -1.30952, 0, 0, 0.486296,-99) , 
NN(
0, 
0, 
-1, -0.326031, 1, -1, 0.376524,-99) , 
25, 76.3257, 1, 0, 0.444149,-99) , 
19, 2.02323, 1, 0, 0.498372,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.0368371);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529286,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49127,-99) , 
16, 75.735, 0, 0, 0.500909,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523797,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428161,-99) , 
11, 1.28571, 1, 0, 0.471022,-99) , 
7, 186.952, 1, 0, 0.498309,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506129,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393099,-99) , 
7, 125.895, 1, 0, 0.484927,-99) , 
NN(
0, 
0, 
-1, -0.326031, 1, -1, 0.37812,-99) , 
25, 76.3257, 1, 0, 0.443937,-99) , 
19, 2.02323, 1, 0, 0.496736,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0250016);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507166,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439081,-99) , 
18, 143.275, 1, 0, 0.50545,-99) , 
NN(
0, 
0, 
-1, 1.20758, 0, -1, 0.471924,-99) , 
7, 186.952, 1, 0, 0.502537,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552388,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407816,-99) , 
18, 49.3285, 1, 0, 0.503339,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543529,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388193,-99) , 
14, 2.54358, 0, 0, 0.40795,-99) , 
25, 57.2786, 1, 0, 0.443797,-99) , 
19, 2.02323, 1, 0, 0.500841,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.0843884);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.904762, 0, 1, 0.558756,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510869,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42955,-99) , 
18, 37.4415, 0, 0, 0.478543,-99) , 
20, 56.7138, 0, 0, 0.508759,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593518,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483935,-99) , 
11, 1.2381, 0, 0, 0.508186,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532807,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440557,-99) , 
11, 1.33333, 1, 0, 0.46714,-99) , 
16, 53.7391, 1, 0, 0.490186,-99) , 
1, 166.614, 1, 0, 0.496167,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.071381);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 38.49, 1, 1, 0.580995,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502763,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40873,-99) , 
15, 0.47619, 1, 0, 0.48742,-99) , 
11, 1.2381, 0, 0, 0.50737,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.651391,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49479,-99) , 
16, 87.6005, 0, 0, 0.542441,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507206,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445809,-99) , 
15, 0.47619, 0, 0, 0.46615,-99) , 
11, 1.33333, 1, 0, 0.489868,-99) , 
16, 53.7391, 1, 0, 0.499871,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0316224);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519495,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461222,-99) , 
15, 0.47619, 1, 0, 0.509293,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500811,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467439,-99) , 
1, 225.043, 1, 0, 0.490958,-99) , 
4, 2.91105, 0, 0, 0.496414,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548756,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400987,-99) , 
24, 28.161, 0, 0, 0.502085,-99) , 
NN(
0, 
0, 
-1, 4.05797, 1, -1, 0.413753,-99) , 
25, 57.2786, 1, 0, 0.446881,-99) , 
19, 2.02323, 1, 0, 0.494989,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0506192);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.904762, 0, 1, 0.593019,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561017,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468582,-99) , 
21, 1.07141, 0, 0, 0.490975,-99) , 
1, 176.968, 1, 0, 0.503624,-99) , 
NN(
0, 
0, 
-1, 32.9989, 0, -1, 0.485081,-99) , 
20, 92.9476, 0, 0, 0.491402,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.0266624);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505904,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.305024,-99) , 
7, 466.901, 1, 0, 0.505492,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507486,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391465,-99) , 
16, 12.2183, 0, 0, 0.441414,-99) , 
17, 4.2413, 1, 0, 0.503989,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577534,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477592,-99) , 
1, 330.643, 0, 0, 0.517797,-99) , 
NN(
0, 
0, 
-1, 1.92185, 0, -1, 0.404608,-99) , 
20, 52.4611, 0, 0, 0.476139,-99) , 
21, 1.78564, 1, 0, 0.501156,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0381511);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537811,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475866,-99) , 
5, 3.67916, 1, 0, 0.524445,-99) , 
NN(
0, 
0, 
-1, 0.57892, 1, -1, 0.422467,-99) , 
0, 0.809635, 1, 0, 0.514937,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526786,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494208,-99) , 
16, 68.8409, 0, 0, 0.503896,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501608,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468565,-99) , 
23, 0.448817, 0, 0, 0.482675,-99) , 
14, -0.975994, 1, 0, 0.492364,-99) , 
14, 2.54318, 0, 0, 0.495684,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0337189);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559481,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494512,-99) , 
1, 135.101, 0, 0, 0.548487,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516891,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448851,-99) , 
19, -0.123382, 0, 0, 0.48433,-99) , 
13, 3.14947, 1, 0, 0.519735,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517893,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490549,-99) , 
9, 144.635, 0, 0, 0.495333,-99) , 
NN(
0, 
0, 
-1, 0.971664, 0, -1, 0.450529,-99) , 
7, 233.61, 1, 0, 0.493475,-99) , 
23, -2.54313, 1, 0, 0.49724,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0424273);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.626904,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491795,-99) , 
11, 1.33333, 1, 0, 0.523058,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529869,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488949,-99) , 
11, 1.28571, 0, 0, 0.500306,-99) , 
16, 75.735, 0, 0, 0.505799,-99) , 
NN(
NN(
0, 
0, 
-1, 1.02207, 0, -1, 0.493669,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547635,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384244,-99) , 
23, -2.24109, 1, 0, 0.420648,-99) , 
6, 1.31238, 1, 0, 0.481239,-99) , 
7, 140.294, 1, 0, 0.501575,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.0408417);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530848,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443837,-99) , 
15, -0.571429, 0, 0, 0.527797,-99) , 
NN(
0, 
0, 
-1, -1.71686, 1, -1, 0.480636,-99) , 
0, 0.619076, 1, 0, 0.519576,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524987,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461054,-99) , 
0, 0.714382, 1, 0, 0.516975,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502648,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452259,-99) , 
7, 118.902, 1, 0, 0.493711,-99) , 
14, 2.00179, 0, 0, 0.502065,-99) , 
14, -1.64557, 1, 0, 0.50737,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.0381603);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 122.563, 0, 1, 0.535739,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511969,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46204,-99) , 
16, 29.986, 0, 0, 0.500387,-99) , 
9, 78.1781, 1, 0, 0.513534,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542092,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493779,-99) , 
0, -0.0469334, 1, 0, 0.514344,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544134,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486313,-99) , 
5, 1.35652, 1, 0, 0.489161,-99) , 
14, 2.4577, 0, 0, 0.495092,-99) , 
14, -1.64557, 1, 0, 0.500677,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0395384);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513727,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442258,-99) , 
24, 19.2432, 0, 0, 0.509168,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509899,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412667,-99) , 
25, 72.7313, 1, 0, 0.486008,-99) , 
1, 143.632, 0, 0, 0.504764,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5034,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.355406,-99) , 
6, 1.29181, 1, 0, 0.484144,-99) , 
NN(
0, 
0, 
-1, -0.627238, 0, -1, 0.342444,-99) , 
7, 80.9702, 0, 0, 0.448183,-99) , 
24, 198.964, 1, 0, 0.503449,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
